name: expense_tracker
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.71.0
  intl: ^0.19.0
  flutter_iconpicker: ^4.0.0
  provider: ^6.1.4
  flutter_colorpicker: ^1.1.0

  firebase_core: ^3.13.0

  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  expense_repo:
   path: packages/expense_repo


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


asssets:
  - assets/avion.png
  - assets/baloncesto.png
  - assets/burguer.png
  - assets/compra.png
  - assets/entretenimiento.png
  - assets/hogar.png
  - assets/huella.png
  - assets/pastel.png
  - assets/telefono.png
  - assets/youtube.png
