name: expense_repo
description: "Repositorio que maneja los datos de gastos y categorias para la aplicacion de gastos."

publish_to: 'none'

version: 1.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
